# Generated by Django 5.0 on 2023-12-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='haDictadoPrograma',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='memoAdjunto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='programaSeleccionado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
