# Generated by Django 5.0 on 2023-12-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_departamento_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='ADistancia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='Diurna',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='FormularioPrincipalCompleto',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='Hibrida',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='Online',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='Otra',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='Presencial',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='Vespertina',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='departamento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='directorPrograma',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='emplazamiento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='mostrarUsoInternoDireccionEstudios',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelProgramaAcademicoSeleccionado',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombrePrograma',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipoProgramaAcademicoSeleccionado',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='value',
            field=models.DateTimeField(null=True),
        ),
    ]
