# Generated by Django 5.0 on 2023-12-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_modulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='haDictadoPrograma',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
