# Generated by Django 5.0 on 2023-12-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_formulario_hadictadoprograma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='Diurna',
            new_name='revisionDGEC',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Otra',
            new_name='revisionDIREST',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='ADistancia',
            new_name='revisionFINANZAS',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Vespertina',
        ),
        migrations.AddField(
            model_name='formulario',
            name='arancel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cedula',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='convocatoria_fecha_inicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='convocatoria_fecha_termino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cupo_maximo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cupo_minimo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='curriculum',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_exAlumnosUSM',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_exAlumnosUSMText',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_funcionariosServiciosPublicos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_funcionariosServiciosPublicosText',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_funcionariosUSM',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_funcionariosUSMText',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_matriculaAnticipada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_matriculaAnticipadaText',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_mujeres',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_mujeresText',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_otros',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_otrosDesc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dcto_otrosText',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='departamento_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='duracion_fecha_inicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='duracion_fecha_termino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='emplazamiento_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='funcionariosServiciosPublicos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='funcionariosServiciosPublicosText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='funcionariosUSM',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='funcionariosUSMText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='jornada_aDistancia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='jornada_diurna',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='jornada_otra',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='jornada_vespertina',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='licenciaMedia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='linkedin_dos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='matriculaAnticipada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='matriculaAnticipadaText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='modalidad_hibrida',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='modalidad_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='modalidad_otra',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='modalidad_pago',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='modalidad_presencial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='mujeres',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='mujeresText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='otra',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='otros',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='otrosDesc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='otrosText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='postulante_cedula',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='postulante_curriculum',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='postulante_licenciaMedia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='postulante_otra',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='profesores',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='programa_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='programa_director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='programa_duracion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='programa_nivel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='programa_numero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='programa_objetivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='programa_resenia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='programa_resenia_dos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='programa_tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='sede',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='departamento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='directorPrograma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='emplazamiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='memoAdjunto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nivelProgramaAcademicoSeleccionado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombrePrograma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tipoProgramaAcademicoSeleccionado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='value',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
