# Generated by Django 5.0 on 2023-12-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_modalidad_pago_rename_diurna_formulario_revisiondgec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Hibrida',
            new_name='hibrida',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Online',
            new_name='online',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Presencial',
            new_name='presencial',
        ),
    ]
